import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navBar/Navbar";
import Navbar_Below from "@/components/navBar/NavBar2";
import SessionWrapper from "@/components/SessionWrapper";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <SessionWrapper>

        <Navbar></Navbar>
        <div className="p-4 lg:px-20 py-3 bg-slate-50   lg:text-sm   text-gray-700 space-y-8">

        <Navbar_Below></Navbar_Below>
        <ToastContainer></ToastContainer>
        </div>
        {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
