import type { Metadata } from "next";
import "./globals.css";
import RootLayout from "@/components/rootLayout";

export const metadata: Metadata = {
  title: "Safe Serf",
  description: "Generated by create next app",
  icons: ["/logo.svg"]
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

      >
        <RootLayout>
          {children}
        </RootLayout>
      </body>
    </html>
  );
}
